/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.preguntas;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import logica.Pregunta;
import millonario.Millonario;

/**
 *
 * @author scot3004
 */
public class Preguntas extends javax.swing.JFrame {

    List<Preguntas> preguntas = new ArrayList<>();
    millonario.Millonario millonario = new Millonario();
    Pregunta actual;
    boolean continuar=true;

    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRespuestas = new javax.swing.JPanel();
        prgTiempo = new javax.swing.JProgressBar();
        txtGanado = new javax.swing.JFormattedTextField();
        btnContinuar = new javax.swing.JButton();
        btnRetirarse = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        txtAsegurado = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRespuestas.setBorder(javax.swing.BorderFactory.createTitledBorder("Presione su respuesta"));
        pnlRespuestas.setLayout(new java.awt.GridLayout(0, 1));

        txtGanado.setEditable(false);
        txtGanado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtGanado.setValue(0);

        btnContinuar.setText("Continuar");
        btnContinuar.setEnabled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnRetirarse.setText("Retirarse");
        btnRetirarse.setEnabled(false);
        btnRetirarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarseActionPerformed(evt);
            }
        });

        btnReset.setText("Iniciar Juego");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblPregunta.setLabelFor(pnlRespuestas);
        lblPregunta.setText("pregunta");

        txtAsegurado.setEditable(false);
        txtAsegurado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtAsegurado.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRespuestas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtAsegurado, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGanado, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prgTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(btnContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetirarse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGanado)
                        .addComponent(txtAsegurado))
                    .addComponent(prgTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnRetirarse)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        pnlRespuestas.removeAll();
        continuar=true;
        cargarPregunta();
        btnContinuar.setEnabled(false);
        btnRetirarse.setEnabled(false);
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        millonario.resetCounter();
        pnlRespuestas.removeAll();
        cargarPregunta();
        btnReset.setEnabled(false);
        continuar=true;
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnRetirarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarseActionPerformed
        btnReset.setEnabled(true);
        btnRetirarse.setEnabled(false);
        btnContinuar.setEnabled(false);
    }//GEN-LAST:event_btnRetirarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    private void responder(ActionEvent evt) {
        if(continuar){
            continuar=false;
            JButton jb = ((JButton) evt.getSource());
            jb.setBackground(Color.orange);
            int index = 0, escogida = -1;
            for (Component c : pnlRespuestas.getComponents()) {
                if (c.equals(jb)) {
                    escogida = index;
                }
                index++;
            }
            resaltarCorrecta();
            if(escogida==actual.getCorrecta()){
                respuestaCorrecta();
            }else{
                respuestaIncorrecta();
            }
            System.out.println("Respuesta escogida: " + actual.getOpciones()[escogida]);
        }
    }
    
    
    private void respuestaCorrecta(){
        btnContinuar.setEnabled(true);
        btnRetirarse.setEnabled(true);
        txtGanado.setValue((millonario.getPreguntaActual()*50000));
        txtAsegurado.setValue((millonario.getAsegurado()*50000));
        //JOptionPane.showMessageDialog(this, "ok");
    }
    
    private void respuestaIncorrecta(){
        btnReset.setEnabled(true);
        btnContinuar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Has ganado "+txtAsegurado.getValue());
        //JOptionPane.showMessageDialog(this, "perdiste");
    }
    
    private void resaltarCorrecta() {
        Component[] c = pnlRespuestas.getComponents();
        c[actual.getCorrecta()].setBackground(Color.GREEN);
    }

    public void cargarPregunta(){
        actual = millonario.getPregunta();
        cargarPregunta(actual);
    }
    
    public void cargarPregunta(Pregunta p) {
        lblPregunta.setText(p.getPregunta());
        String[] opciones = p.getOpciones();
        for (String opcion : opciones) {
            JButton btnOpcion = new JButton(opcion);
            btnOpcion.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    responder(evt);
                }
            });
            pnlRespuestas.add(btnOpcion);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRetirarse;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JPanel pnlRespuestas;
    private javax.swing.JProgressBar prgTiempo;
    private javax.swing.JFormattedTextField txtAsegurado;
    private javax.swing.JFormattedTextField txtGanado;
    // End of variables declaration//GEN-END:variables
}
