/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.preguntas;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import logica.Pregunta;
import millonario.Millonario;

/**
 *
 * @author scot3004
 */
public class Preguntas extends javax.swing.JFrame implements ActionListener,
    PropertyChangeListener {

    List<Preguntas> preguntas = new ArrayList<>();
    millonario.Millonario millonario = new Millonario();
    Pregunta actual;
    boolean continuar = true;
    boolean timer;

    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRespuestas = new javax.swing.JPanel();
        prgTiempo = new javax.swing.JProgressBar();
        txtGanado = new javax.swing.JFormattedTextField();
        btnContinuar = new javax.swing.JButton();
        btnRetirarse = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        txtAsegurado = new javax.swing.JFormattedTextField();
        btnAyuda50 = new javax.swing.JButton();
        btnPista2 = new javax.swing.JButton();
        btnPista1 = new javax.swing.JButton();
        lblAyuda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Millonario");

        pnlRespuestas.setBorder(javax.swing.BorderFactory.createTitledBorder("Presione su respuesta"));
        pnlRespuestas.setLayout(new java.awt.GridLayout(0, 1));

        prgTiempo.setStringPainted(true);

        txtGanado.setEditable(false);
        txtGanado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtGanado.setValue(0);

        btnContinuar.setText("Continuar");
        btnContinuar.setEnabled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnRetirarse.setText("Retirarse");
        btnRetirarse.setEnabled(false);
        btnRetirarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarseActionPerformed(evt);
            }
        });

        btnReset.setText("Iniciar Juego");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblPregunta.setLabelFor(pnlRespuestas);
        lblPregunta.setText("pregunta");

        txtAsegurado.setEditable(false);
        txtAsegurado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtAsegurado.setValue(0);

        btnAyuda50.setText("50/50");
        btnAyuda50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyuda50ActionPerformed(evt);
            }
        });

        btnPista2.setText("Publico");
        btnPista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista2ActionPerformed(evt);
            }
        });

        btnPista1.setText("Llamada");
        btnPista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista1ActionPerformed(evt);
            }
        });

        lblAyuda.setText("Ayuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRespuestas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAsegurado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGanado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prgTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(btnPista2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPista1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAyuda50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetirarse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGanado)
                        .addComponent(txtAsegurado))
                    .addComponent(prgTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnRetirarse)
                    .addComponent(btnAyuda50)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPista2)
                    .addComponent(btnPista1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        pnlRespuestas.removeAll();
        continuar = true;
        lblAyuda.setText("");
        if(cargarPregunta()){
            btnContinuar.setEnabled(false);
            btnRetirarse.setEnabled(false);
            timer=true;
            iniciarTimer(evt);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        actual=null;
        millonario.resetCounter();
        pnlRespuestas.removeAll();
        txtAsegurado.setValue(0);
        txtGanado.setValue(0);
        lblAyuda.setText("");
        btnPista1.setEnabled(true);
        btnPista2.setEnabled(true);
        cargarPregunta();
        for(Component c: pnlRespuestas.getComponents())
            c.setEnabled(true);
        btnReset.setEnabled(false);
        continuar = true;
        millonario.setAyuda_50(true);
        btnAyuda50.setEnabled(true);
        timer=true;
        iniciarTimer(evt);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnRetirarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarseActionPerformed
        btnReset.setEnabled(true);
        btnRetirarse.setEnabled(false);
        btnContinuar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Has ganado " + txtGanado.getValue());
    }//GEN-LAST:event_btnRetirarseActionPerformed

    private void btnAyuda50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyuda50ActionPerformed
        for (Integer i : millonario.incorrectas()) {
            pnlRespuestas.getComponents()[i].setEnabled(false);
        }
        btnAyuda50.setEnabled(false);
    }//GEN-LAST:event_btnAyuda50ActionPerformed

    private void btnPista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista1ActionPerformed
        btnPista1.setEnabled(false);
        lblAyuda.setText(actual.getPista1());
    }//GEN-LAST:event_btnPista1ActionPerformed

    private void btnPista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista2ActionPerformed
        btnPista2.setEnabled(false);
        lblAyuda.setText(actual.getPista2());
    }//GEN-LAST:event_btnPista2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    private void responder(ActionEvent evt) {
        timer=false;
        task.cancel(true);
        if (continuar) {
            continuar = false;
            JButton jb = ((JButton) evt.getSource());
            jb.setBackground(Color.orange);
            int index = 0, escogida = -1;
            for (Component c : pnlRespuestas.getComponents()) {
                if (c.equals(jb)) {
                    escogida = index;
                }
                index++;
            }
            resaltarCorrecta();
            if (escogida == actual.getCorrecta()) {
                respuestaCorrecta();
            } else {
                respuestaIncorrecta();
            }

        }
    }

    private void respuestaCorrecta() {
        btnContinuar.setEnabled(true);
        btnRetirarse.setEnabled(true);
        txtGanado.setValue((millonario.getPreguntaActual() * 50000));
        txtAsegurado.setValue((millonario.getAsegurado() * 50000));
        //JOptionPane.showMessageDialog(this, "ok");
    }

    private void respuestaIncorrecta() {
        btnReset.setEnabled(true);
        btnContinuar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Has ganado " + txtAsegurado.getValue());
        btnAyuda50.setEnabled(false);
        for(Component c:pnlRespuestas.getComponents())
            c.setEnabled(false);
        //JOptionPane.showMessageDialog(this, "perdiste");
    }

    private void resaltarCorrecta() {
        Component[] c = pnlRespuestas.getComponents();
        c[actual.getCorrecta()].setBackground(Color.GREEN);
    }

    public boolean cargarPregunta() {
        //pnlRespuestas = new javax.swing.JPanel();
        //pnlRespuestas.setBorder(javax.swing.BorderFactory.createTitledBorder("Presione su respuesta"));
        //pnlRespuestas.setLayout(new java.awt.GridLayout(0, 1));     
        actual = millonario.getPregunta();
        if(actual==null){
            JOptionPane.showMessageDialog(this, "No hay mas preguntas, ganaste: "+txtGanado.getText());
            timer=false;
            task.cancel(true);
            btnReset.setEnabled(true);
            btnContinuar.setEnabled(false);
            btnRetirarse.setEnabled(false);
            btnAyuda50.setEnabled(false);
            return false;
            
        }
        lblPregunta.setText(actual.getPregunta());
        String[] opciones = actual.getOpciones();
        for (String opcion : opciones) {
            JButton btnOpcion = new JButton(opcion);
            btnOpcion.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    responder(evt);
                }
            });
            pnlRespuestas.add(btnOpcion);
        }
        return true;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    class Task extends SwingWorker<Void, Void> {

        @Override
        public Void doInBackground() {

            int progress = 0;
            // Initialize progress property.
            setProgress(0);
            while (progress < 100&&continuar) {
                // Sleep for up to one second.
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ignore) {
                }
                // Make random progress.
                progress += 1;
                setProgress(Math.min(progress, 100));
            }
            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            if(timer){
                JOptionPane.showMessageDialog(null, "Se acabo el tiempo");
                respuestaIncorrecta();
            }
        }
    }
    
    public void iniciarTimer(ActionEvent evt){
        task = new Task();
        task.addPropertyChangeListener(this);
        task.execute();
    }
    
      /**
   * Invoked when task's progress property changes.
     * @param evt
   */
    @Override
  public void propertyChange(PropertyChangeEvent evt) {
    if ("progress".equals(evt.getPropertyName())) {
      int progress = (Integer) evt.getNewValue();
      prgTiempo.setValue(progress);
    }
  }
private Task task;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda50;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnPista1;
    private javax.swing.JButton btnPista2;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRetirarse;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JPanel pnlRespuestas;
    private javax.swing.JProgressBar prgTiempo;
    private javax.swing.JFormattedTextField txtAsegurado;
    private javax.swing.JFormattedTextField txtGanado;
    // End of variables declaration//GEN-END:variables
}
